default: &default
  adapter: postgresql
  encoding: unicode
  username: deploy
  password: pointer
  pool: 5
development:
  <<: *default
  database: newsapis_development
test:
  <<: *default
  database: newsapis_test
production:
  <<: *default
  database: newsapis_production
